### ISSUE TITLE
Index errors

### ISSUE THREAD

**Issue by SleepingPanda** [j2ghz/repo#1]
Hi I've been getting an index error with fdroid while trying to update your repo even after a full reinstall of fdroid.

[Repositories Screen](https://i.imgur.com/2Je7zty.png)
[Updating Repo Error](https://i.imgur.com/j96phvz.png)

**Comment by j2ghz** [comment]
you have the wrong url, correct is `https://j2ghz.github.io/repo/`

**Comment by SleepingPanda** [comment]
Thank you! Also, thank you for updating the link on the Tachiyomi wiki.
